---
title: 'Chapter 2 - misc packages'
output: github_document
---

# Packages
## Data managment
\begin{description}
 \item [reshape2] Useful melt and dcast function
 \item [dplyr] Easy data managment
 \item [tidyr] Successor of reshape2 to be used along with dplyr
 \item [readr] Fast import of datasets
 \item [readxl] Fast reading of xls and xlsx files
 \item [deSolve]  ODE solver
 \item [Rcpp] Run compiled C++ code in R
 \item [zoo] Useful `na.locf()` function
 \item [fmatch] faster version of `match()`
 \end{description}

## Interactivity
\begin{description}
 \item [manipulate] Generate sliders as in berkeley madonna
 \item [Shiny] Create web apps
 \end{description}

## Plots
\begin{description}
 \item [diagrammeR] Creation of network diagram
 \item [ggplot2] Easily create nice graphics
 \item [lattice] The ggplot2 ancestor
 \item [ggvis] Interactive ggplot
 \item [plot.ly] Another interactive ggplot
 \item [ggpairs] Correlation matrices that look like ggplot
 \item [gridExtra] Useful functions for ggplot2 and lattice
 \item [latticeExtra] Nice ggplot2like() function
 \item [xpose4] Diagnostic plots for NONMEM
 \end{description}

## Reports
\begin{description}
  \item [knitr] Create HTML, doc or pdf while running R code
  \item [rmarkdown] Use the mardown language in R
  \item [xtable] Tables for Latex repports
  \item [ReporteRs] Generate power points from R
  \end{description}

\pagebreak